name: "pre-release"

on: [push, pull_request]

# on:
#   workflow_run:
#     workflows: e2e
#     branches: main
#     types: completed

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: "Pre-release"
        run: |
          FILES="images LICENSE manifest.json package.json remove-paywall.js"
          zip lancaster-online-paywall-remover.zip $FILES

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: ./lancaster-online-paywall-remover.zip
