name: "pre-release"

on:
  workflow_run:
    workflows: ["e2e"]
    types:
      - completed

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # ...
      - name: "Pre-release"
        run: echo "Deploying a development build pre-release!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            images/
            LICENSE
            manifest.json
            package.json
            remove-paywall.js
