name: "release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: "Release"
        run: |
          FILES="images LICENSE manifest.json remove-paywall.js"
          zip -r lancaster-online-paywall-remover.zip $FILES

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ./lancaster-online-paywall-remover.zip
